port: 9000

documents:
  path: /Users/mkrogh/data/writeurl/doc

publish:
  public: /Users/mkrogh/data/writeurl/publish

# Pino logger
# Output goes to stdout.
logger:
  # levels: silent, fatal, error, warn, info, debug, trace
  level: trace
